"""Add multi-tenancy with organizations

Revision ID: b87a96e83060
Revises: d942caed61e2
Create Date: 2025-11-28 19:07:36.328149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87a96e83060'
down_revision: Union[str, Sequence[str], None] = 'd942caed61e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Create organizations table
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('subscription_status', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('max_recipes', sa.Integer(), nullable=True),
    sa.Column('max_distributors', sa.Integer(), nullable=True),
    sa.Column('max_ai_parses_per_month', sa.Integer(), nullable=True),
    sa.Column('ai_parses_used_this_month', sa.Integer(), nullable=True),
    sa.Column('ai_parses_reset_date', sa.DateTime(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("subscription_status IN ('active', 'cancelled', 'past_due', 'trialing')", name='check_subscription_status'),
    sa.CheckConstraint("subscription_tier IN ('free', 'paid', 'enterprise')", name='check_subscription_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )

    # Step 2: Create default organization for existing data
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO organizations (name, slug, subscription_tier, subscription_status, max_recipes, max_distributors, max_ai_parses_per_month, ai_parses_used_this_month)
        VALUES ('Default Organization', 'default', 'free', 'active', 5, 1, 10, 0)
    """))

    # Step 3: Add organization_id columns as nullable first
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('common_products', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('import_batches', sa.Column('organization_id', sa.Integer(), nullable=True))

    # Step 4: Assign all existing records to default organization (id=1)
    conn.execute(sa.text("UPDATE users SET organization_id = 1 WHERE organization_id IS NULL"))
    conn.execute(sa.text("UPDATE common_products SET organization_id = 1 WHERE organization_id IS NULL"))
    conn.execute(sa.text("UPDATE products SET organization_id = 1 WHERE organization_id IS NULL"))
    conn.execute(sa.text("UPDATE recipes SET organization_id = 1 WHERE organization_id IS NULL"))
    conn.execute(sa.text("UPDATE import_batches SET organization_id = 1 WHERE organization_id IS NULL"))

    # Step 5: Make organization_id NOT NULL and add foreign keys
    op.alter_column('users', 'organization_id', nullable=False)
    op.alter_column('common_products', 'organization_id', nullable=False)
    op.alter_column('products', 'organization_id', nullable=False)
    op.alter_column('recipes', 'organization_id', nullable=False)
    op.alter_column('import_batches', 'organization_id', nullable=False)

    # Step 6: Add foreign key constraints
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'common_products', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipes', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'import_batches', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    # Step 7: Drop unique constraint on common_products.common_name (now organization-scoped)
    op.drop_constraint(op.f('common_products_common_name_key'), 'common_products', type_='unique')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'organization_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'organization_id')
    op.drop_constraint(None, 'import_batches', type_='foreignkey')
    op.drop_column('import_batches', 'organization_id')
    op.drop_constraint(None, 'common_products', type_='foreignkey')
    op.create_unique_constraint(op.f('common_products_common_name_key'), 'common_products', ['common_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('common_products', 'organization_id')
    op.drop_table('organizations')
    # ### end Alembic commands ###
